### ISSUE TITLE
Remove binary artefacts from repository

### ISSUE THREAD

**Issue by Mingun** [calgacus/TlkEdit-EE#15]
I think, that we need exclude binary file from git, because it is dramatically increasing repository size. Currently each build produce 2.5 MB jar and now overall repository size is ~37 MB.

We need setup some autobuild, for example, by using GitHub Actions (need learn it).

Currently I suggest not to update `tlkedit.jar`.

**Comment by calgacus** [comment]
We should move the version file into the jar (or make it a URL file on the repo) and then we could host the shell and jar files separately maybe on the vault and steam.
