### ISSUE TITLE
Bic files become unreadable (but still valid)

### ISSUE THREAD

**Issue by WilliamDraco** [calgacus/TlkEdit-EE#19]
We've having an issue with some character files - When first created they can be opened by TLKEdit without issue. However, after some time (or maybe something?) they cease to open correctly.
The characters appear to continue operating as normal in-game, and extraction to json with the nim tools does not show any glaring, obvious corruption.

Attached is an example bic which now fails to be read
[meaculpa.zip](https://github.com/calgacus/TlkEdit-EE/files/4744042/meaculpa.zip)

**Comment by calgacus** [comment]
That file has  a  DescIdentifiedOv field which is of type CExoString - that type has a recommended max size of 1024, but the contents you have in there beyond that.  I think it's the spell description for Teleport_Other.
I can increase the size allowed in TlkEdit but I don't know other tools will oblige.

**Comment by WilliamDraco** [comment]
Dead-on with issue! It's a scroll of Teleport_Other with a description overridden by SetDescription(). Unfortunately the new tlkedit.jar you uploaded does not open the file (Gives the same result as previously).

I chatted with Devs and confirmed the current hard-limit of SetDescription is actually 128*1024, the Pre-EE limit being 8*1024. See image:
![SetDescriptionLimit](https://user-images.githubusercontent.com/29192181/84091627-5d64d080-aa38-11ea-9be5-9b784cbd566f.jpg)

Smaller is "recommended", but technically possible to be up to this size, if you'd like to accommodate that.

**Comment by calgacus** [comment]
OK, done.  Try the new jar and let me know if it works.  Everytime I come back to this project I have to remember to use mvn -install instead of just the menu options and forget to upload the right jar.

**Comment by WilliamDraco** [comment]
The new upload worked. Much appreciated, Thank you!
